language: node_js
node_js:
- 6.0.0
branches:
  only:
  - master

install: npm install

before_script:
- git clone https://github.com/beeronbeard/assorted-solutions-blog.git output
- cd output
- git checkout deploy || git checkout --orphan deploy
- rm -rf public
- cd ..

script: npm run build

after_success:
- git config --global user.name "Travis CI"
- git config --global user.email "travis@travis-ci.org"
- cp -r public/ output/public/
- cd output
- git add -A .
- git commit -m "Fresh blogs for you"
- git push https://${GH_TOKEN}@github.com/beeronbeard/assorted-solutions-blog.git deploy
