language: node_js
node_js:
- 6.0.0
branches:
  only:
  - master

install: npm install

before_script:
- git config --global user.name "Travis CI"
- git config --global user.email "travis@travis-ci.org"

script: npm run build

