language: node_js
node_js:
- 6.0.0
branches:
  only:
  - master

install: npm install

before_script:
- git config --global user.name "BeerOnBeard"
- git config --global user.email "no@no.com"
- sed -i "s/__GH_TOKEN__/${GH_TOKEN}/" _config.yml

script: npm run deploy
